### ISSUE TITLE
(1.14.4) Moar Boat Mod Bugs

### ISSUE THREAD

**Issue by stefanoendergamer25** [jglrxavpok/Moar-Boats#87]
there is a bug in the GUI of the Engine When you mount on the boat the Engine GUI Does Not Open Even if you click with the right button you see to try for this bug thanks

**Comment by jglrxavpok** [comment]
Won't fix, this is a issue due to how Minecraft handles entity interaction.
As of Forge 28.1.90 and Minecraft 1.14.4, the class ProjectileHelper has an issue in the method "func_221273_a", called by Minecraft to find the entity in front of the player:
When the player rides an entity, it checks that the block reach of the player is 0 to determine if it should pick the entity...

**Comment by jglrxavpok** [comment]
A workaround will be opening the menu when trying to access the inventory while riding (like vanilla horses) in the next version
